[package]
name = "tfx-bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
cxx.workspace = true
tfx-core = { path = "../tfx-core", version = "=0.1.0" }

[build-dependencies]
cxx-build.workspace = true
